on:
    push:
        tags:
            - 'v*'
env:
    REGISTRY: ghcr.io

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            packages: write

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Build package
                run: |
                    pyinstaller --clean wechatbot.spec

            -   name: Login to the Github Container registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Login to the Docker official Container registry
                uses: docker/login-action@v3
                with:
                    username: ${{ github.actor }}
                    password: ${{ secrets.DOCKER_OFFICIAL_PASSWORD }}

            -   name: Login to a private Container registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.DOCKER_REGISTRY }}
                    username: ${{ secrets.DOCKER_ACCOUNT }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        docker.io/${{ github.repository }}
                        ${{ env.REGISTRY }}/${{ github.repository }}
                        ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}
                    tags: |
                        type=semver,pattern={{version}}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}

            -   name: Release
                uses: softprops/action-gh-release@v2
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: dist/wechatbot
                    draft: true
                    tag_name: v${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
                    generate_release_notes: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}